version: '3.8'

services:
  database:
    restart: always
    image: mysql:latest
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
  
volumes:
  mysql-datavolume:
    driver: local